#ifndef MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_BUILDER_H
#define MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_BUILDER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_READER_H
#include "magicframe_routego_routera_message_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

#define __magicframe_route_msg_Result_formal_args , magicframe_route_msg_Result_enum_t v0
#define __magicframe_route_msg_Result_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t)

typedef flatbuffers_union_ref_t magicframe_route_msg_Payloads_union_ref_t;
typedef flatbuffers_union_vec_ref_t magicframe_route_msg_Payloads_union_vec_ref_t;
static magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_clone(flatbuffers_builder_t *B, magicframe_route_msg_Payloads_union_t t);

static const flatbuffers_voffset_t __magicframe_route_msg_RouteInfo_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_RouteInfo_ref_t;
static magicframe_route_msg_RouteInfo_ref_t magicframe_route_msg_RouteInfo_clone(flatbuffers_builder_t *B, magicframe_route_msg_RouteInfo_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_RouteInfo, 6)

static const flatbuffers_voffset_t __magicframe_route_msg_PowerCtl_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_PowerCtl_ref_t;
static magicframe_route_msg_PowerCtl_ref_t magicframe_route_msg_PowerCtl_clone(flatbuffers_builder_t *B, magicframe_route_msg_PowerCtl_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_PowerCtl, 4)

static const flatbuffers_voffset_t __magicframe_route_msg_PingPong_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_PingPong_ref_t;
static magicframe_route_msg_PingPong_ref_t magicframe_route_msg_PingPong_clone(flatbuffers_builder_t *B, magicframe_route_msg_PingPong_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_PingPong, 5)

static const flatbuffers_voffset_t __magicframe_route_msg_QueryStatus_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_QueryStatus_ref_t;
static magicframe_route_msg_QueryStatus_ref_t magicframe_route_msg_QueryStatus_clone(flatbuffers_builder_t *B, magicframe_route_msg_QueryStatus_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_QueryStatus, 4)

static const flatbuffers_voffset_t __magicframe_route_msg_Status_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_Status_ref_t;
static magicframe_route_msg_Status_ref_t magicframe_route_msg_Status_clone(flatbuffers_builder_t *B, magicframe_route_msg_Status_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_Status, 4)

static const flatbuffers_voffset_t __magicframe_route_msg_Alerts_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_Alerts_ref_t;
static magicframe_route_msg_Alerts_ref_t magicframe_route_msg_Alerts_clone(flatbuffers_builder_t *B, magicframe_route_msg_Alerts_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_Alerts, 2)

static const flatbuffers_voffset_t __magicframe_route_msg_Payload_required[] = { 0 };
typedef flatbuffers_ref_t magicframe_route_msg_Payload_ref_t;
static magicframe_route_msg_Payload_ref_t magicframe_route_msg_Payload_clone(flatbuffers_builder_t *B, magicframe_route_msg_Payload_table_t t);
__flatbuffers_build_table(flatbuffers_, magicframe_route_msg_Payload, 2)

#define __magicframe_route_msg_RouteInfo_formal_args ,\
  int32_t v0, int32_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3, magicframe_route_msg_Result_enum_t v4, flatbuffers_string_ref_t v5
#define __magicframe_route_msg_RouteInfo_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline magicframe_route_msg_RouteInfo_ref_t magicframe_route_msg_RouteInfo_create(flatbuffers_builder_t *B __magicframe_route_msg_RouteInfo_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_RouteInfo, magicframe_route_msg_RouteInfo_file_identifier, magicframe_route_msg_RouteInfo_type_identifier)

#define __magicframe_route_msg_PowerCtl_formal_args , int32_t v0, flatbuffers_string_ref_t v1, magicframe_route_msg_Result_enum_t v2, flatbuffers_string_ref_t v3
#define __magicframe_route_msg_PowerCtl_call_args , v0, v1, v2, v3
static inline magicframe_route_msg_PowerCtl_ref_t magicframe_route_msg_PowerCtl_create(flatbuffers_builder_t *B __magicframe_route_msg_PowerCtl_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_PowerCtl, magicframe_route_msg_PowerCtl_file_identifier, magicframe_route_msg_PowerCtl_type_identifier)

#define __magicframe_route_msg_PingPong_formal_args ,\
  int64_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, magicframe_route_msg_Result_enum_t v3, flatbuffers_string_ref_t v4
#define __magicframe_route_msg_PingPong_call_args ,\
  v0, v1, v2, v3, v4
static inline magicframe_route_msg_PingPong_ref_t magicframe_route_msg_PingPong_create(flatbuffers_builder_t *B __magicframe_route_msg_PingPong_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_PingPong, magicframe_route_msg_PingPong_file_identifier, magicframe_route_msg_PingPong_type_identifier)

#define __magicframe_route_msg_QueryStatus_formal_args , int64_t v0, flatbuffers_string_ref_t v1, magicframe_route_msg_Result_enum_t v2, flatbuffers_string_ref_t v3
#define __magicframe_route_msg_QueryStatus_call_args , v0, v1, v2, v3
static inline magicframe_route_msg_QueryStatus_ref_t magicframe_route_msg_QueryStatus_create(flatbuffers_builder_t *B __magicframe_route_msg_QueryStatus_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_QueryStatus, magicframe_route_msg_QueryStatus_file_identifier, magicframe_route_msg_QueryStatus_type_identifier)

#define __magicframe_route_msg_Status_formal_args , int32_t v0, int64_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3
#define __magicframe_route_msg_Status_call_args , v0, v1, v2, v3
static inline magicframe_route_msg_Status_ref_t magicframe_route_msg_Status_create(flatbuffers_builder_t *B __magicframe_route_msg_Status_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_Status, magicframe_route_msg_Status_file_identifier, magicframe_route_msg_Status_type_identifier)

#define __magicframe_route_msg_Alerts_formal_args , int32_t v0, flatbuffers_string_ref_t v1
#define __magicframe_route_msg_Alerts_call_args , v0, v1
static inline magicframe_route_msg_Alerts_ref_t magicframe_route_msg_Alerts_create(flatbuffers_builder_t *B __magicframe_route_msg_Alerts_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_Alerts, magicframe_route_msg_Alerts_file_identifier, magicframe_route_msg_Alerts_type_identifier)

#define __magicframe_route_msg_Payload_formal_args , magicframe_route_msg_Payloads_union_ref_t v1
#define __magicframe_route_msg_Payload_call_args , v1
static inline magicframe_route_msg_Payload_ref_t magicframe_route_msg_Payload_create(flatbuffers_builder_t *B __magicframe_route_msg_Payload_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, magicframe_route_msg_Payload, magicframe_route_msg_Payload_file_identifier, magicframe_route_msg_Payload_type_identifier)

static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_NONE(void)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_NONE; uref.value = 0; return uref; }
static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_RouteInfo(magicframe_route_msg_RouteInfo_ref_t ref)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_RouteInfo; uref.value = ref; return uref; }
static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_PingPong(magicframe_route_msg_PingPong_ref_t ref)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_PingPong; uref.value = ref; return uref; }
static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_PowerCtl(magicframe_route_msg_PowerCtl_ref_t ref)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_PowerCtl; uref.value = ref; return uref; }
static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_Status(magicframe_route_msg_Status_ref_t ref)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_Status; uref.value = ref; return uref; }
static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_QueryStatus(magicframe_route_msg_QueryStatus_ref_t ref)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_QueryStatus; uref.value = ref; return uref; }
static inline magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_as_Alerts(magicframe_route_msg_Alerts_ref_t ref)
{ magicframe_route_msg_Payloads_union_ref_t uref; uref.type = magicframe_route_msg_Payloads_Alerts; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, magicframe_route_msg_Payloads)

static magicframe_route_msg_Payloads_union_ref_t magicframe_route_msg_Payloads_clone(flatbuffers_builder_t *B, magicframe_route_msg_Payloads_union_t u)
{
    switch (u.type) {
    case 1: return magicframe_route_msg_Payloads_as_RouteInfo(magicframe_route_msg_RouteInfo_clone(B, (magicframe_route_msg_RouteInfo_table_t)u.value));
    case 2: return magicframe_route_msg_Payloads_as_PingPong(magicframe_route_msg_PingPong_clone(B, (magicframe_route_msg_PingPong_table_t)u.value));
    case 3: return magicframe_route_msg_Payloads_as_PowerCtl(magicframe_route_msg_PowerCtl_clone(B, (magicframe_route_msg_PowerCtl_table_t)u.value));
    case 4: return magicframe_route_msg_Payloads_as_Status(magicframe_route_msg_Status_clone(B, (magicframe_route_msg_Status_table_t)u.value));
    case 5: return magicframe_route_msg_Payloads_as_QueryStatus(magicframe_route_msg_QueryStatus_clone(B, (magicframe_route_msg_QueryStatus_table_t)u.value));
    case 6: return magicframe_route_msg_Payloads_as_Alerts(magicframe_route_msg_Alerts_clone(B, (magicframe_route_msg_Alerts_table_t)u.value));
    default: return magicframe_route_msg_Payloads_as_NONE();
    }
}

__flatbuffers_build_scalar_field(0, flatbuffers_, magicframe_route_msg_RouteInfo_countx, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), magicframe_route_msg_RouteInfo)
__flatbuffers_build_scalar_field(1, flatbuffers_, magicframe_route_msg_RouteInfo_county, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), magicframe_route_msg_RouteInfo)
__flatbuffers_build_string_field(2, flatbuffers_, magicframe_route_msg_RouteInfo_routeid, magicframe_route_msg_RouteInfo)
__flatbuffers_build_string_field(3, flatbuffers_, magicframe_route_msg_RouteInfo_reply, magicframe_route_msg_RouteInfo)
__flatbuffers_build_scalar_field(4, flatbuffers_, magicframe_route_msg_RouteInfo_result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, 1, 1, INT8_C(0), magicframe_route_msg_RouteInfo)
__flatbuffers_build_string_field(5, flatbuffers_, magicframe_route_msg_RouteInfo_reason, magicframe_route_msg_RouteInfo)

static inline magicframe_route_msg_RouteInfo_ref_t magicframe_route_msg_RouteInfo_create(flatbuffers_builder_t *B __magicframe_route_msg_RouteInfo_formal_args)
{
    if (magicframe_route_msg_RouteInfo_start(B)
        || magicframe_route_msg_RouteInfo_countx_add(B, v0)
        || magicframe_route_msg_RouteInfo_county_add(B, v1)
        || magicframe_route_msg_RouteInfo_routeid_add(B, v2)
        || magicframe_route_msg_RouteInfo_reply_add(B, v3)
        || magicframe_route_msg_RouteInfo_reason_add(B, v5)
        || magicframe_route_msg_RouteInfo_result_add(B, v4)) {
        return 0;
    }
    return magicframe_route_msg_RouteInfo_end(B);
}

static magicframe_route_msg_RouteInfo_ref_t magicframe_route_msg_RouteInfo_clone(flatbuffers_builder_t *B, magicframe_route_msg_RouteInfo_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_RouteInfo_start(B)
        || magicframe_route_msg_RouteInfo_countx_pick(B, t)
        || magicframe_route_msg_RouteInfo_county_pick(B, t)
        || magicframe_route_msg_RouteInfo_routeid_pick(B, t)
        || magicframe_route_msg_RouteInfo_reply_pick(B, t)
        || magicframe_route_msg_RouteInfo_reason_pick(B, t)
        || magicframe_route_msg_RouteInfo_result_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_RouteInfo_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, magicframe_route_msg_PowerCtl_mode, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), magicframe_route_msg_PowerCtl)
__flatbuffers_build_string_field(1, flatbuffers_, magicframe_route_msg_PowerCtl_reply, magicframe_route_msg_PowerCtl)
__flatbuffers_build_scalar_field(2, flatbuffers_, magicframe_route_msg_PowerCtl_result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, 1, 1, INT8_C(0), magicframe_route_msg_PowerCtl)
__flatbuffers_build_string_field(3, flatbuffers_, magicframe_route_msg_PowerCtl_reason, magicframe_route_msg_PowerCtl)

static inline magicframe_route_msg_PowerCtl_ref_t magicframe_route_msg_PowerCtl_create(flatbuffers_builder_t *B __magicframe_route_msg_PowerCtl_formal_args)
{
    if (magicframe_route_msg_PowerCtl_start(B)
        || magicframe_route_msg_PowerCtl_mode_add(B, v0)
        || magicframe_route_msg_PowerCtl_reply_add(B, v1)
        || magicframe_route_msg_PowerCtl_reason_add(B, v3)
        || magicframe_route_msg_PowerCtl_result_add(B, v2)) {
        return 0;
    }
    return magicframe_route_msg_PowerCtl_end(B);
}

static magicframe_route_msg_PowerCtl_ref_t magicframe_route_msg_PowerCtl_clone(flatbuffers_builder_t *B, magicframe_route_msg_PowerCtl_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_PowerCtl_start(B)
        || magicframe_route_msg_PowerCtl_mode_pick(B, t)
        || magicframe_route_msg_PowerCtl_reply_pick(B, t)
        || magicframe_route_msg_PowerCtl_reason_pick(B, t)
        || magicframe_route_msg_PowerCtl_result_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_PowerCtl_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, magicframe_route_msg_PingPong_reqtime, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), magicframe_route_msg_PingPong)
__flatbuffers_build_string_field(1, flatbuffers_, magicframe_route_msg_PingPong_reply, magicframe_route_msg_PingPong)
__flatbuffers_build_string_field(2, flatbuffers_, magicframe_route_msg_PingPong_version, magicframe_route_msg_PingPong)
__flatbuffers_build_scalar_field(3, flatbuffers_, magicframe_route_msg_PingPong_result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, 1, 1, INT8_C(0), magicframe_route_msg_PingPong)
__flatbuffers_build_string_field(4, flatbuffers_, magicframe_route_msg_PingPong_reason, magicframe_route_msg_PingPong)

static inline magicframe_route_msg_PingPong_ref_t magicframe_route_msg_PingPong_create(flatbuffers_builder_t *B __magicframe_route_msg_PingPong_formal_args)
{
    if (magicframe_route_msg_PingPong_start(B)
        || magicframe_route_msg_PingPong_reqtime_add(B, v0)
        || magicframe_route_msg_PingPong_reply_add(B, v1)
        || magicframe_route_msg_PingPong_version_add(B, v2)
        || magicframe_route_msg_PingPong_reason_add(B, v4)
        || magicframe_route_msg_PingPong_result_add(B, v3)) {
        return 0;
    }
    return magicframe_route_msg_PingPong_end(B);
}

static magicframe_route_msg_PingPong_ref_t magicframe_route_msg_PingPong_clone(flatbuffers_builder_t *B, magicframe_route_msg_PingPong_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_PingPong_start(B)
        || magicframe_route_msg_PingPong_reqtime_pick(B, t)
        || magicframe_route_msg_PingPong_reply_pick(B, t)
        || magicframe_route_msg_PingPong_version_pick(B, t)
        || magicframe_route_msg_PingPong_reason_pick(B, t)
        || magicframe_route_msg_PingPong_result_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_PingPong_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, magicframe_route_msg_QueryStatus_reqtime, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), magicframe_route_msg_QueryStatus)
__flatbuffers_build_string_field(1, flatbuffers_, magicframe_route_msg_QueryStatus_reply, magicframe_route_msg_QueryStatus)
__flatbuffers_build_scalar_field(2, flatbuffers_, magicframe_route_msg_QueryStatus_result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, 1, 1, INT8_C(0), magicframe_route_msg_QueryStatus)
__flatbuffers_build_string_field(3, flatbuffers_, magicframe_route_msg_QueryStatus_reason, magicframe_route_msg_QueryStatus)

static inline magicframe_route_msg_QueryStatus_ref_t magicframe_route_msg_QueryStatus_create(flatbuffers_builder_t *B __magicframe_route_msg_QueryStatus_formal_args)
{
    if (magicframe_route_msg_QueryStatus_start(B)
        || magicframe_route_msg_QueryStatus_reqtime_add(B, v0)
        || magicframe_route_msg_QueryStatus_reply_add(B, v1)
        || magicframe_route_msg_QueryStatus_reason_add(B, v3)
        || magicframe_route_msg_QueryStatus_result_add(B, v2)) {
        return 0;
    }
    return magicframe_route_msg_QueryStatus_end(B);
}

static magicframe_route_msg_QueryStatus_ref_t magicframe_route_msg_QueryStatus_clone(flatbuffers_builder_t *B, magicframe_route_msg_QueryStatus_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_QueryStatus_start(B)
        || magicframe_route_msg_QueryStatus_reqtime_pick(B, t)
        || magicframe_route_msg_QueryStatus_reply_pick(B, t)
        || magicframe_route_msg_QueryStatus_reason_pick(B, t)
        || magicframe_route_msg_QueryStatus_result_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_QueryStatus_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, magicframe_route_msg_Status_status, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), magicframe_route_msg_Status)
__flatbuffers_build_scalar_field(1, flatbuffers_, magicframe_route_msg_Status_time, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), magicframe_route_msg_Status)
__flatbuffers_build_string_field(2, flatbuffers_, magicframe_route_msg_Status_position, magicframe_route_msg_Status)
__flatbuffers_build_string_field(3, flatbuffers_, magicframe_route_msg_Status_screenid, magicframe_route_msg_Status)

static inline magicframe_route_msg_Status_ref_t magicframe_route_msg_Status_create(flatbuffers_builder_t *B __magicframe_route_msg_Status_formal_args)
{
    if (magicframe_route_msg_Status_start(B)
        || magicframe_route_msg_Status_time_add(B, v1)
        || magicframe_route_msg_Status_status_add(B, v0)
        || magicframe_route_msg_Status_position_add(B, v2)
        || magicframe_route_msg_Status_screenid_add(B, v3)) {
        return 0;
    }
    return magicframe_route_msg_Status_end(B);
}

static magicframe_route_msg_Status_ref_t magicframe_route_msg_Status_clone(flatbuffers_builder_t *B, magicframe_route_msg_Status_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_Status_start(B)
        || magicframe_route_msg_Status_time_pick(B, t)
        || magicframe_route_msg_Status_status_pick(B, t)
        || magicframe_route_msg_Status_position_pick(B, t)
        || magicframe_route_msg_Status_screenid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_Status_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, magicframe_route_msg_Alerts_alerttype, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), magicframe_route_msg_Alerts)
__flatbuffers_build_string_field(1, flatbuffers_, magicframe_route_msg_Alerts_reason, magicframe_route_msg_Alerts)

static inline magicframe_route_msg_Alerts_ref_t magicframe_route_msg_Alerts_create(flatbuffers_builder_t *B __magicframe_route_msg_Alerts_formal_args)
{
    if (magicframe_route_msg_Alerts_start(B)
        || magicframe_route_msg_Alerts_alerttype_add(B, v0)
        || magicframe_route_msg_Alerts_reason_add(B, v1)) {
        return 0;
    }
    return magicframe_route_msg_Alerts_end(B);
}

static magicframe_route_msg_Alerts_ref_t magicframe_route_msg_Alerts_clone(flatbuffers_builder_t *B, magicframe_route_msg_Alerts_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_Alerts_start(B)
        || magicframe_route_msg_Alerts_alerttype_pick(B, t)
        || magicframe_route_msg_Alerts_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_Alerts_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, magicframe_route_msg_Payload)
__flatbuffers_build_union_table_value_field(flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, RouteInfo, magicframe_route_msg_RouteInfo)
__flatbuffers_build_union_table_value_field(flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, PingPong, magicframe_route_msg_PingPong)
__flatbuffers_build_union_table_value_field(flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, PowerCtl, magicframe_route_msg_PowerCtl)
__flatbuffers_build_union_table_value_field(flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, Status, magicframe_route_msg_Status)
__flatbuffers_build_union_table_value_field(flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, QueryStatus, magicframe_route_msg_QueryStatus)
__flatbuffers_build_union_table_value_field(flatbuffers_, magicframe_route_msg_Payload_type, magicframe_route_msg_Payloads, Alerts, magicframe_route_msg_Alerts)

static inline magicframe_route_msg_Payload_ref_t magicframe_route_msg_Payload_create(flatbuffers_builder_t *B __magicframe_route_msg_Payload_formal_args)
{
    if (magicframe_route_msg_Payload_start(B)
        || magicframe_route_msg_Payload_type_add_value(B, v1)
        || magicframe_route_msg_Payload_type_add_type(B, v1.type)) {
        return 0;
    }
    return magicframe_route_msg_Payload_end(B);
}

static magicframe_route_msg_Payload_ref_t magicframe_route_msg_Payload_clone(flatbuffers_builder_t *B, magicframe_route_msg_Payload_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (magicframe_route_msg_Payload_start(B)
        || magicframe_route_msg_Payload_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, magicframe_route_msg_Payload_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_BUILDER_H */
