#ifndef MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_VERIFIER_H
#define MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_READER_H
#include "magicframe_routego_routera_message_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int magicframe_route_msg_RouteInfo_verify_table(flatcc_table_verifier_descriptor_t *td);
static int magicframe_route_msg_PowerCtl_verify_table(flatcc_table_verifier_descriptor_t *td);
static int magicframe_route_msg_PingPong_verify_table(flatcc_table_verifier_descriptor_t *td);
static int magicframe_route_msg_QueryStatus_verify_table(flatcc_table_verifier_descriptor_t *td);
static int magicframe_route_msg_Status_verify_table(flatcc_table_verifier_descriptor_t *td);
static int magicframe_route_msg_Alerts_verify_table(flatcc_table_verifier_descriptor_t *td);
static int magicframe_route_msg_Payload_verify_table(flatcc_table_verifier_descriptor_t *td);

static int magicframe_route_msg_Payloads_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, magicframe_route_msg_RouteInfo_verify_table); /* RouteInfo */
    case 2: return flatcc_verify_union_table(ud, magicframe_route_msg_PingPong_verify_table); /* PingPong */
    case 3: return flatcc_verify_union_table(ud, magicframe_route_msg_PowerCtl_verify_table); /* PowerCtl */
    case 4: return flatcc_verify_union_table(ud, magicframe_route_msg_Status_verify_table); /* Status */
    case 5: return flatcc_verify_union_table(ud, magicframe_route_msg_QueryStatus_verify_table); /* QueryStatus */
    case 6: return flatcc_verify_union_table(ud, magicframe_route_msg_Alerts_verify_table); /* Alerts */
    default: return flatcc_verify_ok;
    }
}

static int magicframe_route_msg_RouteInfo_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* countx */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* county */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* routeid */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* reply */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* result */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 5, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_RouteInfo_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_RouteInfo_identifier, &magicframe_route_msg_RouteInfo_verify_table);
}

static inline int magicframe_route_msg_RouteInfo_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_RouteInfo_type_identifier, &magicframe_route_msg_RouteInfo_verify_table);
}

static inline int magicframe_route_msg_RouteInfo_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_RouteInfo_verify_table);
}

static inline int magicframe_route_msg_RouteInfo_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_RouteInfo_verify_table);
}

static int magicframe_route_msg_PowerCtl_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* mode */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* reply */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* result */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_PowerCtl_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_PowerCtl_identifier, &magicframe_route_msg_PowerCtl_verify_table);
}

static inline int magicframe_route_msg_PowerCtl_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_PowerCtl_type_identifier, &magicframe_route_msg_PowerCtl_verify_table);
}

static inline int magicframe_route_msg_PowerCtl_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_PowerCtl_verify_table);
}

static inline int magicframe_route_msg_PowerCtl_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_PowerCtl_verify_table);
}

static int magicframe_route_msg_PingPong_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* reqtime */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* reply */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* version */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* result */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 4, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_PingPong_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_PingPong_identifier, &magicframe_route_msg_PingPong_verify_table);
}

static inline int magicframe_route_msg_PingPong_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_PingPong_type_identifier, &magicframe_route_msg_PingPong_verify_table);
}

static inline int magicframe_route_msg_PingPong_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_PingPong_verify_table);
}

static inline int magicframe_route_msg_PingPong_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_PingPong_verify_table);
}

static int magicframe_route_msg_QueryStatus_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* reqtime */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* reply */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* result */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_QueryStatus_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_QueryStatus_identifier, &magicframe_route_msg_QueryStatus_verify_table);
}

static inline int magicframe_route_msg_QueryStatus_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_QueryStatus_type_identifier, &magicframe_route_msg_QueryStatus_verify_table);
}

static inline int magicframe_route_msg_QueryStatus_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_QueryStatus_verify_table);
}

static inline int magicframe_route_msg_QueryStatus_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_QueryStatus_verify_table);
}

static int magicframe_route_msg_Status_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* status */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* time */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* position */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* screenid */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_Status_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_Status_identifier, &magicframe_route_msg_Status_verify_table);
}

static inline int magicframe_route_msg_Status_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_Status_type_identifier, &magicframe_route_msg_Status_verify_table);
}

static inline int magicframe_route_msg_Status_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_Status_verify_table);
}

static inline int magicframe_route_msg_Status_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_Status_verify_table);
}

static int magicframe_route_msg_Alerts_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* alerttype */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_Alerts_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_Alerts_identifier, &magicframe_route_msg_Alerts_verify_table);
}

static inline int magicframe_route_msg_Alerts_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_Alerts_type_identifier, &magicframe_route_msg_Alerts_verify_table);
}

static inline int magicframe_route_msg_Alerts_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_Alerts_verify_table);
}

static inline int magicframe_route_msg_Alerts_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_Alerts_verify_table);
}

static int magicframe_route_msg_Payload_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &magicframe_route_msg_Payloads_union_verifier) /* type */)) return ret;
    return flatcc_verify_ok;
}

static inline int magicframe_route_msg_Payload_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_Payload_identifier, &magicframe_route_msg_Payload_verify_table);
}

static inline int magicframe_route_msg_Payload_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, magicframe_route_msg_Payload_type_identifier, &magicframe_route_msg_Payload_verify_table);
}

static inline int magicframe_route_msg_Payload_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &magicframe_route_msg_Payload_verify_table);
}

static inline int magicframe_route_msg_Payload_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &magicframe_route_msg_Payload_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_VERIFIER_H */
