#ifndef MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_READER_H
#define MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct magicframe_route_msg_RouteInfo_table *magicframe_route_msg_RouteInfo_table_t;
typedef struct magicframe_route_msg_RouteInfo_table *magicframe_route_msg_RouteInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_RouteInfo_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_RouteInfo_mutable_vec_t;
typedef const struct magicframe_route_msg_PowerCtl_table *magicframe_route_msg_PowerCtl_table_t;
typedef struct magicframe_route_msg_PowerCtl_table *magicframe_route_msg_PowerCtl_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_PowerCtl_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_PowerCtl_mutable_vec_t;
typedef const struct magicframe_route_msg_PingPong_table *magicframe_route_msg_PingPong_table_t;
typedef struct magicframe_route_msg_PingPong_table *magicframe_route_msg_PingPong_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_PingPong_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_PingPong_mutable_vec_t;
typedef const struct magicframe_route_msg_QueryStatus_table *magicframe_route_msg_QueryStatus_table_t;
typedef struct magicframe_route_msg_QueryStatus_table *magicframe_route_msg_QueryStatus_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_QueryStatus_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_QueryStatus_mutable_vec_t;
typedef const struct magicframe_route_msg_Status_table *magicframe_route_msg_Status_table_t;
typedef struct magicframe_route_msg_Status_table *magicframe_route_msg_Status_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_Status_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_Status_mutable_vec_t;
typedef const struct magicframe_route_msg_Alerts_table *magicframe_route_msg_Alerts_table_t;
typedef struct magicframe_route_msg_Alerts_table *magicframe_route_msg_Alerts_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_Alerts_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_Alerts_mutable_vec_t;
typedef const struct magicframe_route_msg_Payload_table *magicframe_route_msg_Payload_table_t;
typedef struct magicframe_route_msg_Payload_table *magicframe_route_msg_Payload_mutable_table_t;
typedef const flatbuffers_uoffset_t *magicframe_route_msg_Payload_vec_t;
typedef flatbuffers_uoffset_t *magicframe_route_msg_Payload_mutable_vec_t;
#ifndef magicframe_route_msg_RouteInfo_file_identifier
#define magicframe_route_msg_RouteInfo_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_RouteInfo_file_identifier */
#ifndef magicframe_route_msg_RouteInfo_identifier
#define magicframe_route_msg_RouteInfo_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_RouteInfo_type_hash ((flatbuffers_thash_t)0x314a706)
#define magicframe_route_msg_RouteInfo_type_identifier "\x06\xa7\x14\x03"
#ifndef magicframe_route_msg_PowerCtl_file_identifier
#define magicframe_route_msg_PowerCtl_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_PowerCtl_file_identifier */
#ifndef magicframe_route_msg_PowerCtl_identifier
#define magicframe_route_msg_PowerCtl_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_PowerCtl_type_hash ((flatbuffers_thash_t)0xc17c797f)
#define magicframe_route_msg_PowerCtl_type_identifier "\x7f\x79\x7c\xc1"
#ifndef magicframe_route_msg_PingPong_file_identifier
#define magicframe_route_msg_PingPong_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_PingPong_file_identifier */
#ifndef magicframe_route_msg_PingPong_identifier
#define magicframe_route_msg_PingPong_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_PingPong_type_hash ((flatbuffers_thash_t)0xf1d3779b)
#define magicframe_route_msg_PingPong_type_identifier "\x9b\x77\xd3\xf1"
#ifndef magicframe_route_msg_QueryStatus_file_identifier
#define magicframe_route_msg_QueryStatus_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_QueryStatus_file_identifier */
#ifndef magicframe_route_msg_QueryStatus_identifier
#define magicframe_route_msg_QueryStatus_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_QueryStatus_type_hash ((flatbuffers_thash_t)0x2f8efdad)
#define magicframe_route_msg_QueryStatus_type_identifier "\xad\xfd\x8e\x2f"
#ifndef magicframe_route_msg_Status_file_identifier
#define magicframe_route_msg_Status_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_Status_file_identifier */
#ifndef magicframe_route_msg_Status_identifier
#define magicframe_route_msg_Status_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_Status_type_hash ((flatbuffers_thash_t)0x85469227)
#define magicframe_route_msg_Status_type_identifier "\x27\x92\x46\x85"
#ifndef magicframe_route_msg_Alerts_file_identifier
#define magicframe_route_msg_Alerts_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_Alerts_file_identifier */
#ifndef magicframe_route_msg_Alerts_identifier
#define magicframe_route_msg_Alerts_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_Alerts_type_hash ((flatbuffers_thash_t)0xcfd9a146)
#define magicframe_route_msg_Alerts_type_identifier "\x46\xa1\xd9\xcf"
#ifndef magicframe_route_msg_Payload_file_identifier
#define magicframe_route_msg_Payload_file_identifier flatbuffers_identifier
#endif
/* deprecated, use magicframe_route_msg_Payload_file_identifier */
#ifndef magicframe_route_msg_Payload_identifier
#define magicframe_route_msg_Payload_identifier flatbuffers_identifier
#endif
#define magicframe_route_msg_Payload_type_hash ((flatbuffers_thash_t)0x4671697d)
#define magicframe_route_msg_Payload_type_identifier "\x7d\x69\x71\x46"

typedef int8_t magicframe_route_msg_Result_enum_t;
__flatbuffers_define_integer_type(magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, 8)
#define magicframe_route_msg_Result_Success ((magicframe_route_msg_Result_enum_t)INT8_C(0))
#define magicframe_route_msg_Result_Failure ((magicframe_route_msg_Result_enum_t)INT8_C(1))

static inline const char *magicframe_route_msg_Result_name(magicframe_route_msg_Result_enum_t value)
{
    switch (value) {
    case magicframe_route_msg_Result_Success: return "Success";
    case magicframe_route_msg_Result_Failure: return "Failure";
    default: return "";
    }
}

static inline int magicframe_route_msg_Result_is_known_value(magicframe_route_msg_Result_enum_t value)
{
    switch (value) {
    case magicframe_route_msg_Result_Success: return 1;
    case magicframe_route_msg_Result_Failure: return 1;
    default: return 0;
    }
}


typedef uint8_t magicframe_route_msg_Payloads_union_type_t;
__flatbuffers_define_integer_type(magicframe_route_msg_Payloads, magicframe_route_msg_Payloads_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, magicframe_route_msg_Payloads)
#define magicframe_route_msg_Payloads_NONE ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(0))
#define magicframe_route_msg_Payloads_RouteInfo ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(1))
#define magicframe_route_msg_Payloads_PingPong ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(2))
#define magicframe_route_msg_Payloads_PowerCtl ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(3))
#define magicframe_route_msg_Payloads_Status ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(4))
#define magicframe_route_msg_Payloads_QueryStatus ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(5))
#define magicframe_route_msg_Payloads_Alerts ((magicframe_route_msg_Payloads_union_type_t)UINT8_C(6))

static inline const char *magicframe_route_msg_Payloads_type_name(magicframe_route_msg_Payloads_union_type_t type)
{
    switch (type) {
    case magicframe_route_msg_Payloads_NONE: return "NONE";
    case magicframe_route_msg_Payloads_RouteInfo: return "RouteInfo";
    case magicframe_route_msg_Payloads_PingPong: return "PingPong";
    case magicframe_route_msg_Payloads_PowerCtl: return "PowerCtl";
    case magicframe_route_msg_Payloads_Status: return "Status";
    case magicframe_route_msg_Payloads_QueryStatus: return "QueryStatus";
    case magicframe_route_msg_Payloads_Alerts: return "Alerts";
    default: return "";
    }
}

static inline int magicframe_route_msg_Payloads_is_known_type(magicframe_route_msg_Payloads_union_type_t type)
{
    switch (type) {
    case magicframe_route_msg_Payloads_NONE: return 1;
    case magicframe_route_msg_Payloads_RouteInfo: return 1;
    case magicframe_route_msg_Payloads_PingPong: return 1;
    case magicframe_route_msg_Payloads_PowerCtl: return 1;
    case magicframe_route_msg_Payloads_Status: return 1;
    case magicframe_route_msg_Payloads_QueryStatus: return 1;
    case magicframe_route_msg_Payloads_Alerts: return 1;
    default: return 0;
    }
}


struct magicframe_route_msg_RouteInfo_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_RouteInfo_vec_len(magicframe_route_msg_RouteInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_RouteInfo_table_t magicframe_route_msg_RouteInfo_vec_at(magicframe_route_msg_RouteInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_RouteInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_RouteInfo)

__flatbuffers_define_scalar_field(0, magicframe_route_msg_RouteInfo, countx, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, magicframe_route_msg_RouteInfo, county, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(2, magicframe_route_msg_RouteInfo, routeid, 0)
__flatbuffers_define_string_field(3, magicframe_route_msg_RouteInfo, reply, 0)
__flatbuffers_define_scalar_field(4, magicframe_route_msg_RouteInfo, result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, INT8_C(0))
__flatbuffers_define_string_field(5, magicframe_route_msg_RouteInfo, reason, 0)

struct magicframe_route_msg_PowerCtl_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_PowerCtl_vec_len(magicframe_route_msg_PowerCtl_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_PowerCtl_table_t magicframe_route_msg_PowerCtl_vec_at(magicframe_route_msg_PowerCtl_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_PowerCtl_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_PowerCtl)

__flatbuffers_define_scalar_field(0, magicframe_route_msg_PowerCtl, mode, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(1, magicframe_route_msg_PowerCtl, reply, 0)
__flatbuffers_define_scalar_field(2, magicframe_route_msg_PowerCtl, result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, INT8_C(0))
__flatbuffers_define_string_field(3, magicframe_route_msg_PowerCtl, reason, 0)

struct magicframe_route_msg_PingPong_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_PingPong_vec_len(magicframe_route_msg_PingPong_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_PingPong_table_t magicframe_route_msg_PingPong_vec_at(magicframe_route_msg_PingPong_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_PingPong_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_PingPong)

__flatbuffers_define_scalar_field(0, magicframe_route_msg_PingPong, reqtime, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_string_field(1, magicframe_route_msg_PingPong, reply, 0)
__flatbuffers_define_string_field(2, magicframe_route_msg_PingPong, version, 0)
__flatbuffers_define_scalar_field(3, magicframe_route_msg_PingPong, result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, INT8_C(0))
__flatbuffers_define_string_field(4, magicframe_route_msg_PingPong, reason, 0)

struct magicframe_route_msg_QueryStatus_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_QueryStatus_vec_len(magicframe_route_msg_QueryStatus_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_QueryStatus_table_t magicframe_route_msg_QueryStatus_vec_at(magicframe_route_msg_QueryStatus_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_QueryStatus_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_QueryStatus)

__flatbuffers_define_scalar_field(0, magicframe_route_msg_QueryStatus, reqtime, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_string_field(1, magicframe_route_msg_QueryStatus, reply, 0)
__flatbuffers_define_scalar_field(2, magicframe_route_msg_QueryStatus, result, magicframe_route_msg_Result, magicframe_route_msg_Result_enum_t, INT8_C(0))
__flatbuffers_define_string_field(3, magicframe_route_msg_QueryStatus, reason, 0)

struct magicframe_route_msg_Status_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_Status_vec_len(magicframe_route_msg_Status_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_Status_table_t magicframe_route_msg_Status_vec_at(magicframe_route_msg_Status_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_Status_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_Status)

__flatbuffers_define_scalar_field(0, magicframe_route_msg_Status, status, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, magicframe_route_msg_Status, time, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_string_field(2, magicframe_route_msg_Status, position, 0)
__flatbuffers_define_string_field(3, magicframe_route_msg_Status, screenid, 0)

struct magicframe_route_msg_Alerts_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_Alerts_vec_len(magicframe_route_msg_Alerts_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_Alerts_table_t magicframe_route_msg_Alerts_vec_at(magicframe_route_msg_Alerts_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_Alerts_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_Alerts)

__flatbuffers_define_scalar_field(0, magicframe_route_msg_Alerts, alerttype, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(1, magicframe_route_msg_Alerts, reason, 0)

struct magicframe_route_msg_Payload_table { uint8_t unused__; };

static inline size_t magicframe_route_msg_Payload_vec_len(magicframe_route_msg_Payload_vec_t vec)
__flatbuffers_vec_len(vec)
static inline magicframe_route_msg_Payload_table_t magicframe_route_msg_Payload_vec_at(magicframe_route_msg_Payload_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(magicframe_route_msg_Payload_table_t, vec, i, 0)
__flatbuffers_table_as_root(magicframe_route_msg_Payload)

__flatbuffers_define_union_field(flatbuffers_, 1, magicframe_route_msg_Payload, type, magicframe_route_msg_Payloads, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* MAGICFRAME_ROUTEGO_ROUTERA_MESSAGE_READER_H */
