# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Msg

import flatbuffers

class GPS(object):
    __slots__ = ['_tab']

    # GPS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GPS
    def Log(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # GPS
    def Lat(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateGPS(builder, log, lat):
    builder.Prep(4, 8)
    builder.PrependFloat32(lat)
    builder.PrependFloat32(log)
    return builder.Offset()
