# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Msg

import flatbuffers

class UpgradeEv(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUpgradeEv(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UpgradeEv()
        x.Init(buf, n + offset)
        return x

    # UpgradeEv
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UpgradeEv
    def Softver(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UpgradeEv
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UpgradeEvStart(builder): builder.StartObject(2)
def UpgradeEvAddSoftver(builder, softver): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(softver), 0)
def UpgradeEvAddUrl(builder, url): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)
def UpgradeEvEnd(builder): return builder.EndObject()
