# automatically generated by the FlatBuffers compiler, do not modify

# namespace: msg

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Status(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Status
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Status
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Status
    def Screenid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def StatusStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddStatus(builder, status): builder.PrependInt32Slot(0, status, 0)
def StatusAddStatus(builder, status):
    """This method is deprecated. Please switch to AddStatus."""
    return AddStatus(builder, status)
def AddTime(builder, time): builder.PrependInt64Slot(1, time, 0)
def StatusAddTime(builder, time):
    """This method is deprecated. Please switch to AddTime."""
    return AddTime(builder, time)
def AddPosition(builder, position): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def StatusAddPosition(builder, position):
    """This method is deprecated. Please switch to AddPosition."""
    return AddPosition(builder, position)
def AddScreenid(builder, screenid): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(screenid), 0)
def StatusAddScreenid(builder, screenid):
    """This method is deprecated. Please switch to AddScreenid."""
    return AddScreenid(builder, screenid)
def End(builder): return builder.EndObject()
def StatusEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)