# automatically generated by the FlatBuffers compiler, do not modify

# namespace: school

import flatbuffers

class School(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSchool(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = School()
        x.Init(buf, n + offset)
        return x

    # School
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # School
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # School
    def Students(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Student import Student
            obj = Student()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # School
    def StudentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SchoolStart(builder): builder.StartObject(2)
def SchoolAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def SchoolAddStudents(builder, students): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(students), 0)
def SchoolStartStudentsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SchoolEnd(builder): return builder.EndObject()
