# automatically generated by the FlatBuffers compiler, do not modify

# namespace: school

import flatbuffers

class Student(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStudent(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Student()
        x.Init(buf, n + offset)
        return x

    # Student
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Student
    def Number(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # Student
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StudentStart(builder): builder.StartObject(2)
def StudentAddNumber(builder, number): builder.PrependInt16Slot(0, number, 0)
def StudentAddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def StudentEnd(builder): return builder.EndObject()
