# automatically generated by the FlatBuffers compiler, do not modify

# namespace: msg

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PingPong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PingPong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPingPong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PingPong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PingPong
    def Reqtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PingPong
    def Reply(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PingPong
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PingPong
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PingPong
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(5)
def PingPongStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddReqtime(builder, reqtime): builder.PrependInt64Slot(0, reqtime, 0)
def PingPongAddReqtime(builder, reqtime):
    """This method is deprecated. Please switch to AddReqtime."""
    return AddReqtime(builder, reqtime)
def AddReply(builder, reply): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reply), 0)
def PingPongAddReply(builder, reply):
    """This method is deprecated. Please switch to AddReply."""
    return AddReply(builder, reply)
def AddVersion(builder, version): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)
def PingPongAddVersion(builder, version):
    """This method is deprecated. Please switch to AddVersion."""
    return AddVersion(builder, version)
def AddResult(builder, result): builder.PrependInt8Slot(3, result, 0)
def PingPongAddResult(builder, result):
    """This method is deprecated. Please switch to AddResult."""
    return AddResult(builder, result)
def AddReason(builder, reason): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)
def PingPongAddReason(builder, reason):
    """This method is deprecated. Please switch to AddReason."""
    return AddReason(builder, reason)
def End(builder): return builder.EndObject()
def PingPongEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)