# automatically generated by the FlatBuffers compiler, do not modify

# namespace: msg

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Alerts(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Alerts()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAlerts(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Alerts
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Alerts
    def Alerttype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Alerts
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def AlertsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddAlerttype(builder, alerttype): builder.PrependInt32Slot(0, alerttype, 0)
def AlertsAddAlerttype(builder, alerttype):
    """This method is deprecated. Please switch to AddAlerttype."""
    return AddAlerttype(builder, alerttype)
def AddReason(builder, reason): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)
def AlertsAddReason(builder, reason):
    """This method is deprecated. Please switch to AddReason."""
    return AddReason(builder, reason)
def End(builder): return builder.EndObject()
def AlertsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)