# automatically generated by the FlatBuffers compiler, do not modify

# namespace: msg

class Payloads(object):
    NONE = 0
    RouteInfo = 1
    PingPong = 2
    PowerCtl = 3
    Status = 4
    QueryStatus = 5
    Alerts = 6

