#!/bin/bash

sudo apt-get install libc6-dev-i386
sudo apt-get install lib32z1 lib32ncurses5
sudo apt-get install libuuid1:i386
sudo apt-get install cmake
sudo apt-get install libncurses5-dev libncursesw5-dev
sudo apt install bc
sudo apt-get install xz-utils
sudo apt-get install automake
sudo apt-get install libtool
sudo apt-get install libevdev-dev
sudo apt-get install pkg-config
